### PR TITLE
Fix compatibility issue with RxJS v6

### PR DESCRIPTION
**Pull request by SergeyKharchenko**

### CODE REVIEW

**Comment by smithad15** [comment]
Thanks for catching this!

**Comment by SergeyKharchenko** [comment]
When can we expect new version?

**Comment by maplion** [comment]
@smithad15 I am echoing @SergeyKharchenko: How soon can we get an rxjs-6-compatible version released?

**Comment by smithad15** [comment]
Released in v9.0.1

**Pull request merged**
